name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setenv
        run: |
          echo "::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Build
        run: |
          mkdir build
          find . -name \*.meta > metaList

      - name: create-unitypackage
        uses: pCYSl5EDgo/create-unitypackage@v1
        with:
          package-path: build/MeshHoleShrinker-${{ env.RELEASE_VERSION }}.unitypackage
          include-files: metaList

      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: build/MeshHoleShrinker-${{ env.RELEASE_VERSION }}.unitypackage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
